# Generated by Django 4.2.6 on 2024-02-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField(max_length=200)),
                ('raqamingiz', models.IntegerField()),
                ('bizgasavollar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Konsultatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismingiz', models.CharField(max_length=150)),
                ('raqam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaysi_dastur_uchun', models.CharField(max_length=200)),
                ('qayerdansiz', models.CharField(max_length=150)),
            ],
        ),
    ]
